name: deploy

on:
  push:
  schedule:
    - cron: '0 15 * * *' # 毎日 0 時

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: extract branch name
        run: echo "::set-output name=name::${GITHUB_REF#refs/heads/}"
        id: extract-branch
      - name: echo branch
        run: echo ${{ steps.extract-branch.outputs.name }}

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '16.x'
      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build
        env:
          VITE_STAGE: production
          VITE_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: yarn run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: koki.me
          force_orphan: true
