name: release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *' # 毎日 0 時

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile

      - run: yarn run build
        env:
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ vars.GA_MEASUREMENT_ID }}
      - run: yarn run export

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: koki.me
          force_orphan: true
